services:
  docker:
    container_name: jenkins-docker-demo
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs-demo:/certs/client
      - jenkins-data-demo:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      jenkins-demo:
        aliases:
          - docker
    command: --storage-driver overlay2
  jenkins-blueocean:
    container_name: jenkins-blueocean-demo
    build:
      context: .
      dockerfile: Dockerfile.blueocean
    restart: on-failure
    networks:
      - jenkins-demo
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8082:8080
      - 50001:50000
    volumes:
      - jenkins-data-demo:/var/jenkins_home
      - jenkins-docker-certs-demo:/certs/client:ro
networks:
  jenkins-demo:
    name: jenkins-demo
volumes:
  jenkins-docker-certs-demo:
    name: jenkins-docker-certs-demo
  jenkins-data-demo:
    name: jenkins-data-demo
